meta_product_name: “Par-Tee”

meta_title: “Par-Tee – The ultimate pub golf experience”

meta_description: “The ultimate pub golf experience. Designed for your fun and enjoyment”

meta_image: “cover.png” # should exist in `app/assets/images/`
